# Generated by Django 3.0.4 on 2020-03-17 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20200317_1242'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='message',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='product',
            name='email',
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1),
        ),
    ]
